### ISSUE TITLE
dataset is too large

### ISSUE THREAD

**Issue by Zhao-Qihao** [WaywayPao/RiskBench#1]
hello, It's really a nice project. But a problem is that the dataset is too large, I could not download it. Could you please provide a small dataset split from the original RiskBench dataset?

**Comment by WaywayPao** [comment]
Thank you for your kind words and for your interest in the project!
We understand that the dataset size can be a challenge.

We will work on providing a smaller split of the original RiskBench dataset that can be more manageable for download.
Please stay tuned for an update, and we will notify you as soon as the smaller version is available

**Comment by WaywayPao** [comment]
@Zhao-Qihao 
Here is the link to the RiskBench small interactive dataset: [link](https://drive.google.com/file/d/11ZVLlnvLNzl8Oq-jAzBmon6xW53hCc2X/view?usp=sharing). The compressed size is 1.36 GB.

If you have any further questions, feel free to reach out to me.

**Comment by Zhao-Qihao** [comment]
@WaywayPao 
Thank you very much for providing the smaller split of the RiskBench dataset. I appreciate your prompt response and effort to make the dataset more manageable for download
